### ISSUE TITLE
Partial toEnum function

### ISSUE THREAD

**Issue by gitfoxi** [haskell/c2hs#120]
c2hs makes this for me:

    toEnum unmatched = error ("McdResult.toEnum: Cannot match " ++ show unmatched)

I think it would be good to avoid `error` by defining some catch-all code. it could be like

    toEnum unmatched = MyCatchAll unmatched

Also looks like `pred` and `succ` can fall off the rails. Is there a safer way to define these?

**Comment by ian-ross** [comment]
@gitfoxi This behaviour is the behaviour required of bounded `Enum` instances by the Haskell Report.  From Section 6.3.4 of the Haskell 2010 Report:

----------

For any type that is an instance of class `Bounded` as well as `Enum`, the following should hold:

 * The calls `succ maxBound` and `pred minBound` should result in a runtime error.
 * `fromEnum` and `toEnum` should give a runtime error if the result value is not representable in the result type. For example, `toEnum 7 :: Bool` is an error.

----------

That means that we can't really do what you request directly for `Enum` instances.  We have discussed having a seperate `CEnum` class for conversion between C enumerations and Haskell enumerated types which would provide only `toEnum` and `fromEnum` methods, but that's not something that's been done yet, since it would require a change to the core libraries.
