### ISSUE TITLE
C2HS parse error on Windows 7

### ISSUE THREAD

**Issue by deech** [haskell/c2hs#126]
Hi,
I'm running into an error getting c2hs to parse a file on Windows 7. 

I originally asked on haskell-cafe with no response and I'm not sure how to proceed. 

Here's the original message: https://mail.haskell.org/pipermail/haskell-cafe/2015-March/118474.html

Thanks!

**Comment by ian-ross** [comment]
@deech This is almost certainly not something I'm going to be able to fix by changing C2HS.  From what you said in your email to me, this sounds more like a problem with your Cabal/GHC/GCC installation.

I guess there are really two problems here.  The first is that Cabal is choosing the "wrong" GCC and there's no obvious way to make it choose a different one (I don't even know if it makes sense to do that anyway).  The second problem is that Cabal doesn't provide any way to pass options to subsidiary build tools like C2HS, i.e. there's nothing that allows you to say something like `cabal ... --c2hs-options="--cpp=C:\MinGW\bin\gcc.exe" ...` and cause C2HS to be told which compiler to use for preprocessing globally within that invocation of Cabal (there is an outstanding Cabal issue to add this feature: https://github.com/haskell/cabal/issues/1223).

As I think I said in an earlier email, I'm only just starting to work with Haskell on Windows (there's another C2HS issue for Windows that I need to look at, which is the only reason I'm doing it at all!).  I've had some success using Neil Mitchell and Michael Snoyman's MinGHC (https://github.com/fpco/minghc), although I've also ended up installing Cygwin because some packages use the GNU autotools as well as Cabal for setting up Haskell packages...  Anyway, MinGHC seems like a more reliable approach than the Haskell Platform.

Sorry I can't be of more help, but I honestly don't think there's much I can do about this from within C2HS.  If you have any more questions or thoughts, I'd be interested to hear them.

For reference, you said:

> I have identified the issue, but not sure how to fix it. The problem is that Cabal is choosing the `gcc` 
> that came with Haskell Platform (4.6.3) instead of the newer one I installed with the latest MinGW
> installer(4.8.1).
>
> The problem went away when I changed the c2hs command to:
> "c:\Users\deech\AppData\Roaming\cabal\bin\c2hs.exe" 
>    "--cpp=C:\MinGW\bin\gcc.exe"
>    ...
>
> My "Path" variable shows that "C:\MinGW\bin" is ahead of the Haskell platform bin directory so I'm 
> not why it's picking the older version of gcc.

**Comment by deech** [comment]
Ah, I didn't know you were the `c2hs` maintainer or I would not have posted here. Sorry. Thanks for your earlier responses and I'll try again with MinGHC and see how I make out.

**Comment by ian-ross** [comment]
No, no, that's fine.  If you're stuck, I'm very happy to help as far as possible.  I just don't think that this problem is going to be fixable by doing things to C2HS.  Once control gets to C2HS from Cabal, all the choices of tools are made and there's not much that C2HS can do but play along!
