### ISSUE TITLE
Allow user to specify size used for malloc in "+" function param types

### ISSUE THREAD

**Issue by sinelaw** [haskell/c2hs#140]
Currently c2hs attempts to calculate sizes and uses them implicitly when generating code for "+" parameter directives. 
Sometimes I want to specify a different size (for when the inferred size is wrong or when it's not possible to determine from the code).
One possibility is to require the argument to implement `Storable` and then use the `sizeOf` function. This approach also fixes the inconsistency for when a type *does already have a Storable instance*, in which case possibly different sizes will be used in different contexts by c2hs.
See baf1d2a85c87a6884d7d4ebcc50b2ef2e8756883 for a possible implementation.

**Comment by ian-ross** [comment]
This is a good idea.  Let me think about the best way to deal with it.

**Comment by ian-ross** [comment]
@sinelaw I've had a look at the fix you wrote, and I think that in principle it's a good idea (using `Storable` instances where possible), but I'm less keen on *requiring* a `Storable` instance to be written.  One of the goals of C2HS is to make writing "normal" bindings very easy, so it tries to work out C structure sizes itself without requiring the user to write `Storable` instances to make those things explicit.  As you rightly note, this doesn't always work, and in fact there are cases where this breaks not only the size calculations, but also structure offset calculations for `get` and `set` hooks (the one case I know of where this happens and it's really hard to deal with is where you have nested structures and the C compiler inserts extra padding that can't be determined from any information available in any of the Haskell FFI libraries).

The `sizeOf` function in C2HS is definitely something of a bodge, but it does have the dual benefits of working most of the time and not requiring anything extra from the user.  You can write `{#pointer *blah as Blah foreign newtype#}` and most of the time you can then `get` and `set` fields in `blah` structures to your heart's content, without having to write a `Storable` instance.

In this case, I would be tempted (although it's pretty ugly) to allow the user to enable the functionality you've implemented by saying something like `+S` instead of `+`, explicitly marking that they're prepared to supply a `Storable` instance for the type.  Maybe we could also have a `+<number>` syntax to explicitly give the size to allocate.  However, in neither of those additional cases would the structure offset calculations be done any differently, so

**Comment by sinelaw** [comment]
Sounds reasonable. Should I take a shot at implementing it?

**Comment by ian-ross** [comment]
@sinelaw  You're welcome to do it (PRs are gold!), though I should be able to get to it on Thursday if things go as I hope with "real" work.  Adding stuff to the C2HS AST and parser is pretty easy, but it will probably be quicker for me to do it just because I've been in there lots of times before.

**Comment by sinelaw** [comment]
Great! Leaving it for you to enjoy then ;)

**Comment by ian-ross** [comment]
I've done this as described above.  It will be in release 0.27.1, which should go onto Hackage a little later today.

**Comment by sinelaw** [comment]
Awesome! Thanks!
